apiVersion: v1
kind: Service
metadata:
  name: estadisticas-service
  labels:
    app: estadisticas-service
spec:
  # ClusterIP: http://estadisticas-service:8006
  type: ClusterIP
  selector:
    app: estadisticas-service
  ports:
    - name: http
      protocol: TCP
      port: 8006
      targetPort: 8006
